<?php

/*
 * Plugin Name: JoolenPromotionModal4
 *
 * Copyright(c) joolen inc. All Rights Reserved.
 *
 * https://www.joolen.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\JoolenPromotionModal4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\JoolenPromotionModal4\Entity\PromotionModal;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PromotionModalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionModalRepository extends AbstractRepository
{
    /**
     * PromotionModalRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, PromotionModal::class);
    }

    /**
     * @param int $id
     *
     * @return null|PromotionModal
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
