<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEl0l1iq\EccubeEccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEl0l1iq/EccubeEccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerEl0l1iq.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerEl0l1iq\EccubeEccube_KernelProdContainer::class, EccubeEccube_KernelProdContainer::class, false);
}

return new \ContainerEl0l1iq\EccubeEccube_KernelProdContainer([
    'container.build_hash' => 'El0l1iq',
    'container.build_id' => 'bf1a988d',
    'container.build_time' => 1652173200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEl0l1iq');
