<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\OrderCsvCustomize4\Repository;


use Eccube\Entity\Master\OrderItemType;
use Eccube\Entity\Order;
use Eccube\Repository\OrderItemRepository as BaseOrderItemRepository;
use Doctrine\ORM\QueryBuilder;
use Eccube\Doctrine\Query\QueryCustomizer;
use Eccube\Repository\QueryKey;
use Eccube\Request\Context;
use Eccube\Repository\MemberRepository;
use Eccube\Entity\OrderItem;

/**
 * ProductClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemExtensionRepository extends BaseOrderItemRepository
{

    public function getListAddType(Order $Order, OrderItemType $OrderItemType)
    {
        // second level cacheを効かせるためfindByで取得
        $Results = [];

        $qb = $this->createQueryBuilder('oi');
        $qb->select('oi');
        $qb->where('oi.Order = :Order')->setParameter('Order', $Order);
        $qb->andWhere('oi.OrderItemType = :OrderItemType')->setParameter('OrderItemType', $OrderItemType);

        $Results = $qb ->getQuery()->getResult();

        return $Results;
    }
}
